### ISSUE TITLE
Add how to run this application in Visual Studio section 

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#118]
Current readme file has instruction to run the service to check it out. But for development purpose the services need to run from `Visual Studio`. The instruction to run it from `Visual Studio` is missing. We should add it with screenshots.

We should also add `Seq` url in the readme file. We are using `Seq` for storing and processing logs.

**Comment by ratanparai** [comment]
Moving this issue to the backlog as currently there is no plan when we will start it. If anyone interested, please comments

**Comment by NitaiBanik** [comment]
I want to work on this issue.

cc: @ratanparai

**Comment by NitaiBanik** [comment]
#448
