### ISSUE TITLE
Implement Ocelot API Gateway 

### ISSUE THREAD

**Issue by kmrul** [OpenCodeFoundation/eSchool#125]
We need to implement API Gateway. How about is using Oecelot API gateway? @ratanparai @mahedee @iamkajal

**Comment by ratanparai** [comment]
API gateway is low priority for now. We will use the API gateway when we have a few services and frontend. our current development priorities are defined from needs. 

Thanks for the suggestion.

**Comment by ratanparai** [comment]
We are going to GraphQL gateway. So, closing this issue.
