### ISSUE TITLE
About WiKi

### ISSUE THREAD

**Issue by iamkajal** [OpenCodeFoundation/eSchool#14]
There is no wiki or wiki page currently. need setting up a wiki to describe NEWS / ANNOUNCEMENTS, Questions, Roadmap, Setting up your development environment for eSchool etc.

**Comment by ratanparai** [comment]
@iamkajal : Nice idea. I am thinking about using `slack` for news and announcements . For others things we should have wiki documentations. Although this is very important , currently I am busy setting up `enrollment` service as a reference service for developing other services. 

If you want to work on this wiki, please let me know. I will try my best to help you

**Comment by ratanparai** [comment]
We do not need wiki now. Closing this. will reopen when it's needed
