### ISSUE TITLE
Dev machine requirements

### ISSUE THREAD

**Issue by iamkajal** [OpenCodeFoundation/eSchool#16]
There no Dev machine requirements for the development environment. need to describe the dev machine requirement in a wiki page.

 i. e . 1. Windows dev machine {Recommended Hardware requirements, Software requirements for Windows are}. 2. Mac dev machine{Recommended Hardware requirements, Software requirements for Mac are} etc.

**Comment by ratanparai** [comment]
closed by PR #47
