### ISSUE TITLE
Initial implementation of Blazor frontend service

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#172]
The initial version will be written in Blazor web assembly and consume the APIs directly without any API gateway / BFF. 

The initial UI will be simple.

**Comment by hard-rox** [comment]
Since I played a little with Blazor. I am interested to kickstart Blazor Frontend Service. Any guideline?

**Comment by ratanparai** [comment]
Thanks for your interest.

> On 7 Jul, 2020, at 12:28 AM, Md. Rasedur Rahman Roxy <notifications@github.com> wrote:
> 
> 
> Since I played a little with Blazor. I am interested to kickstart Blazor Frontend Service. Any guideline?
> 
> 

Currently there is no guideline or timeline for the task. But if you are interested, feel free to send a PR so that we can review

**Comment by ratanparai** [comment]
The initial implementation of the Blazor Web assembly-based frontend is already implemented. 

Closing the issue
