### ISSUE TITLE
Class Routine Builder

### ISSUE THREAD

**Issue by cseshohag** [OpenCodeFoundation/eSchool#25]
>Faculty/Teachers can make a class routine for students. 
>Routine will be auto-generated for students. 
>Every can see the routine.

**Comment by ratanparai** [comment]
@cseshohag : Thanks for the suggestion. We will work in this feature in near future. Currently we are working on student enrollment. 

If you want to work on this feature, please let me know. I will try my best to help you regarding this.

**Comment by cseshohag** [comment]
@Ratan Parai <contact@ratanparai.com> :  I want to work on this feature.

Best Regards

*Md. Solaiman Shohag*

**Comment by ratanparai** [comment]
@cseshohag : Great. Feel free to send a `WIP` `PR` with this service. You can check the `Enrollment` service for guideline for how to create a new service. 

**NOTE:** `WIP` or `Work in Progress` pull request is a pull request which is still in progress. This way I can help you while you work on the service and suggest modification if needed and guide you.

**Comment by ratanparai** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.

**Comment by cseshohag** [comment]
Okey Bhai.

Best Regards

*Md. Solaiman Shohag*
