### ISSUE TITLE
Taking attendance using face detection 

### ISSUE THREAD

**Issue by mhmohona** [OpenCodeFoundation/eSchool#26]
There will be camera which will taking attendance automatically by detecting students face using computer vision.

**Comment by ratanparai** [comment]
@mhmohona: Thanks for the suggestion. I think we can use `ML.NET` to achieve this. I am not expert in this field. If you want you can check if it is possible with `ML.NET` and let us know. 

Please let me know if you need any kind of help regarding this.

**Comment by mhmohona** [comment]
I am thinking to do this with Azure.
Okay, I will give a try to do this with ML.Net then.

**Comment by ratanparai** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
