### ISSUE TITLE
I want to work on Library Management Service

### ISSUE THREAD

**Issue by sohan093007** [OpenCodeFoundation/eSchool#350]

**Comment by ratanparai** [comment]
In the Miro board there is no Library Management Service events planned. Can you share your plan please?

**Comment by sohan093007** [comment]
![Library](https://user-images.githubusercontent.com/2952337/114262987-b7da0f00-9a04-11eb-91f7-d740abbf8af0.PNG)
The following feature will be added
Library Rules for borrowing Book 
1. Rules for Student 
2. Rules for Teacher
3. Rules for Office Stuff

**Comment by ratanparai** [comment]
Can you share some of the initial business events you can think off?

**Comment by sohan093007** [comment]
![image](https://user-images.githubusercontent.com/2952337/115121591-54884800-9fd5-11eb-8a34-91a7f9af6b92.png)

**Comment by sohan093007** [comment]
Those are some ideas. Those Ideas may need discussion.
