### ISSUE TITLE
I want to implement Student Management Service

### ISSUE THREAD

**Issue by NitaiBanik** [OpenCodeFoundation/eSchool#358]
I have found some ideas about student management service in eSchool-Domain analysis. I think it would be great if get some instruction from you before the initial implementation.

//cc: @mahedee @ratanparai @aftabkajal

**Comment by mahedee** [comment]
What is your plan @NitaiBanik ?

**Comment by NitaiBanik** [comment]
Bhai, I didn't make any concrete plan yet. I just went through the miro board.

**Comment by ratanparai** [comment]
Closing this issue as we are not developing student management service for now.
