### ISSUE TITLE
Result Processing Service Initial Implementation 

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#361]

**Comment by shahanazdev19** [comment]
I will do it.

**Comment by ratanparai** [comment]
@shahanazdev19: Have you started working on this yet? Can you please share your progress?

**Comment by shahanazdev19** [comment]
I am reviewing code and will start developing. For corona, when I started
home office, my all setup removed for office setup. Now preparing
environment. After that will start development. Sorry for missing the last
class. I thought it was at night. Didn't check clearly the schedule. Insha
Allah shal join next class.


Regards,
Shahanaz Sultana

শনি, ১৭ এপ্রিল, ২০২১ তারিখে ৯:৪১ PM টায় এ Ratan Sunder Parai <
***@***.***> লিখেছেন:
