### ISSUE TITLE
Certificate Registration Service Initial Implementation 

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#362]

**Comment by NitaiBanik** [comment]
I want to work in this Certificate Registration Service.

**Comment by ratanparai** [comment]
@NitaiBanik: Okay assigning the task to you. Please try to avoid big PR. For example, You can create a simple API project - `CertificateRegistration.API` with a `HelloWorldController` that will return the string *HelloWorld*. 

This is easier for both coder and reviewer.

**Comment by ratanparai** [comment]
@NitaiBanik: I think the service name is wrong. Sorry somehow, I have missed it before! Is should be `Certificate Processing` service.
