### ISSUE TITLE
Cannot run project in docker

### ISSUE THREAD

**Issue by shahanazdev19** [OpenCodeFoundation/eSchool#387]
![docker run failed](https://user-images.githubusercontent.com/48450494/115882645-c564af80-a46e-11eb-88a0-a82fadef34c7.PNG)

**Comment by ratanparai** [comment]
@shahanazdev19: please make sure docker for desktop is running before you run the command

**Comment by shahanazdev19** [comment]
![Uploading docker is running.PNG…]()

**Comment by shahanazdev19** [comment]
Docker is running correctly Vai

**Comment by ratanparai** [comment]
@shahanazdev19: Please wait until the image is uploaded before you comment. I can not check the image you have uploaded. 

Can you please use default terminal, not git bash to run the command and share the response?

**Comment by shahanazdev19** [comment]
At last I see that my project was build and run in default docker, so I am closing the issue now.
