### ISSUE TITLE
Add docker files for ExamManagement, LibraryManagement, and ResultProcessing services 

### ISSUE THREAD

**Issue by NitaiBanik** [OpenCodeFoundation/eSchool#517]
Currently ExamManagement, LibraryManagement, ResultProcessing don't have any docker files. Also, these services are not added to the solution file.

cc: @ratanparai @mahedee

**Comment by NitaiBanik** [comment]
Implemeting in ```pr``` #518

**Comment by ratanparai** [comment]
closed in PR #518
