### ISSUE TITLE
Choose frontend framework 

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#6]
We need to choose a frontend framework for the `eSchool` project. 

Although `Angular ` is most common here in **Bangladesh**, `React` is also getting popularity. Personally I am preferring `React` over `Angular` for this project. In my short discussion with @mahedee, he is also giving high precedence to `React` over `Angular`.

Please share and discuss your opinion in this issue here.

**Comment by iamkajal** [comment]
We will discuss it in the next meeting.

**Comment by punkouter2018** [comment]
Blazor

**Comment by ratanparai** [comment]
We have decided to will go with Blazor for now.
