### ISSUE TITLE
Set default namespace rule and change Identity project's namespace

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/eSchool#8]
There is no rule set for `namespace` **prefix** for the project. I am thinking about using `OpenCodeFoundation.eSchool` as the **prefix** of all `dotnet` applications. 

Also currently `namespace` for the `Identity` project is `Identity.API`. We need to change the `Identity` project's namespace to `OpenCodeFoundation.eSchool.Identity.API`

**Comment by iamkajal** [comment]
I think it should be better.
